name: Update Bundle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use'
        required: true
        type: string
        default: null
  workflow_call:
    inputs:
      version:
        description: 'Version to use'
        required: true
        type: string
        default: null

jobs:
  update-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update Bundle
        run: |
          version=${{ inputs.version }}
          patches_asset_url="https://github.com/indrastorms/Dropped-Patches/releases/latest/download/patches-${version}.rvp"
          signatureDownloadUrl="https://github.com/indrastorms/Dropped-Patches/releases/latest/download/patches-${version}.rvp.asc"
          
          info_dict=$(cat <<EOF
          {
              "createdAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
              "description": "Release version ${version}",
              "downloadUrl": "${patches_asset_url}",
              "signatureDownloadUrl": "${signatureDownloadUrl}",
              "version": "${version}"
          }
          EOF
          )

          echo "bundle_file=dropped-patches-bundle.json" >> $GITHUB_ENV
          echo "$info_dict" > "${{ env.bundle_file }}"
          echo "Latest release information saved to ${{ env.bundle_file }}"

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ env.bundle_file }}
          git commit -m "update ${{ env.bundle_file }} [skip ci]"
          git pull

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
